# Generated by Django 4.0.5 on 2022-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonserv',
            options={'verbose_name': 'pokedex', 'verbose_name_plural': 'pokedex'},
        ),
        migrations.AddField(
            model_name='pokemonserv',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonserv',
            name='tipo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonserv',
            name='imagen',
            field=models.ImageField(upload_to='pokedexserv'),
        ),
    ]
