# Generated by Django 4.0.5 on 2022-08-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk', models.IntegerField()),
                ('defen', models.IntegerField()),
                ('spp', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estadistica',
                'verbose_name_plural': 'Estadisticas',
            },
        ),
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='selectgrupo')),
                ('descripcion', models.CharField(max_length=1000)),
                ('peso', models.FloatField()),
                ('evolucion', models.BooleanField(default=True)),
                ('estadisticas', models.ManyToManyField(to='selectgrupo.estadisticaspokemon')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectgrupo.tipopokemon')),
            ],
            options={
                'verbose_name': 'pokemon',
                'verbose_name_plural': 'pokemons',
            },
        ),
    ]
